### PR TITLE
Commands: Add "wen" alias for "plan"

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
This is kind of a meme on Discord where "wen" is commonly used when
asking for features. As this is the purpose of the "plan" command, an
alias "wen" could make the use of "plan" much funnier.

### CODE REVIEW

**Comment by ZikiFlicky** [comment]
!wen merged

**Comment by ZikiFlicky** [comment]
it needs to be added to the help page

**Comment by kleinesfilmroellchen** [comment]
@ZikiFlicky Most aliases are not part of the FAQ, such as the old !pr and others.

**Comment by bgianfo** [comment]
I don't think this is make much sense as an alias for `!plan` as the response doesn't make sense for the `!wen` meme. That being said I see no harm in the alias existing until someone decides to level up the meme to it's own dedicated command.

**Pull request merged**
