### PR TITLE
Add !soytineres command

### PR DESCRIPTION
**Pull request by sin-ack**
:^).

### CODE REVIEW

**Comment by bgianfo** [comment]
Not sure how I feel about meme's in the bot 😄

**Comment by IdanHo** [comment]
LGTM, but not sure about memes as well

**Comment by sin-ack** [comment]
I only had it in mind because I was reminded of Kling's `!SOytinereS` message, feel free to close it if you think it isn't appropriate.

**Comment by bgianfo** [comment]
Meh, I guess it's easy enough to rip it out later.

**Pull request merged**
