### PR TITLE
UserCommand: Fix updating embeds in dms

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
Also threw in the second commit as a "why not"

**Comment by bgianfo** [comment]
This isn't very readable, can you put the type assertion in a local variable outside of the `if` body?

**Comment by u9g** [comment]
> This isn't very readable, can you put the type assertion in a local variable outside of the `if` body?

done

**Comment by bgianfo** [comment]
Thanks! 🥰

**Pull request merged**
