### PR TITLE
Add !plan to check if a feature is part of the SerenityOS plan

### PR DESCRIPTION
**Pull request by Dexesttp**
Example usage :

User: `!plan hardware acceleration`

Bot :
```
> Will SerenityOS support hardware acceleration?
Maybe. Maybe not. There is no plan.
(source: <https://github.com/SerenityOS/serenity/blob/master/Documentation/FAQ.md>)
```

Also works without arguments to use the original "Will SerenityOS support `$THING`?" question.

### CODE REVIEW

**Comment by bgianfo** [comment]
Can you please make fix the commit message to follow the `<subsustem>: title` convention. Maybe: `Commands: Add !plan to check if a feature is part of the SerenityOS plan`

**Comment by Dexesttp** [comment]
Done! I based it on the commit history (which seemed all over the place), but we can totally start doing things properly from now on :^)

**Comment by bgianfo** [comment]
> I based it on the commit history (which seemed all over the place), but we can totally start doing things properly from now on :^)

We've been using it since the beginning, not sure what you mean.

**Comment by Dexesttp** [comment]
Wow that's one strict linter. It should be good now.

**Comment by bgianfo** [comment]
Thanks for the contribution! 👍

**Pull request merged**
