### PR TITLE
Small docs tweaks

### PR DESCRIPTION
**Pull request by linusg**
Two small tweaks that helped me getting started.

### CODE REVIEW

**Review by IdanHo — APPROVED** [review]

**Comment by bgianfo** [comment]
The `guild_id` is optional, which is why it was omitted from the docs.

**Comment by linusg** [comment]
As mentioned in the commit message, I was unable to use the bot before adding it, so if there's some way to make it work with the default, that should be documented as well.

**Comment by bgianfo** [comment]
I see, it's because the `!test262` command you were working on relies on emojis which are fetched from the guild and need. I guess I got by in the past when working on commands without specific guild access needs. 🤷

**Comment by linusg** [comment]
oh, that makes sense! In hindsight I should've tried some different commands... thanks for clarifying :+1:

**Pull request merged**
